### ISSUE TITLE
Elaborating signalk-simple-notifications...

### ISSUE THREAD

**Issue by preeve9534** [sbender9/signalk-simple-notifications#1]
Hi Scott.  I needed a limits based notifier with a slightly more elaborate configuration and user interface than signalk-simple-notifications.  I produced something for my own consumption based on your work - then realised that it may be useful to others.  If you have no problem with me releasing it, I'll do so - with full acknowledgement of your inspiration of course.  The plugin is at:

https://github.com/preeve9534/signalk-threshold-notifier

Regards, Paul

**Comment by sbender9** [comment]
Please go ahead and release it!

**Comment by preeve9534** [comment]
Thanks.  Will do.
